/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The stable category of a coding agent failure.
 */

export const AgentErrorKind = {
    LLM: 'llm',
    COMPACTION: 'compaction',
    AGENT: 'agent',
    INVALID_INPUT: 'invalid_input',
    SESSION_CLOSED: 'session_closed',
    INVALID_STATE: 'invalid_state',
    TOOL_EXECUTION: 'tool_execution',
    INTERRUPTED: 'interrupted',
    TOOL_ROUNDS_EXHAUSTED: 'tool_rounds_exhausted',
    TASK: 'task',
    EVENT_STREAM: 'event_stream'
} as const;

export type AgentErrorKind = typeof AgentErrorKind[keyof typeof AgentErrorKind];
