/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentErrorData } from './agent-error-data';
// May contain unused imports in some cases
// @ts-ignore
import type { FailoverContinuation } from './failover-continuation';
// May contain unused imports in some cases
// @ts-ignore
import type { TokenUsage } from './token-usage';

/**
 * One move the root session made to a fallback route, as the stream reported it from the route it moved to.
 */
export interface AgentSessionRouteFailover {
    /**
     * The `provider/model` that failed.
     */
    'from': string;
    /**
     * The `provider/model` the prompt continued on.
     */
    'to': string;
    /**
     * How many routes the prompt had moved through, this one included.
     */
    'attempt': number;
    /**
     * The failure that ended the previous route.
     */
    'error': AgentErrorData;
    /**
     * What the prompt spent on the failed route. Already in the session\'s and the prompt\'s totals through that route\'s committed answers: a breakdown, not an addition.
     */
    'usage': TokenUsage;
    'cost_usd_micros'?: number;
    /**
     * Milliseconds the prompt spent waiting on the failed route\'s model.
     */
    'inference_ms': number;
    /**
     * Milliseconds the prompt spent running tools on the failed route.
     */
    'tool_ms': number;
    'continuation': FailoverContinuation;
}
