/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Usage } from './usage';

/**
 * What one descendant session spent, as its own events reported it.
 */
export interface AgentSessionDescendantAccount {
    /**
     * The session that spawned it.
     */
    'parent': string;
    /**
     * The provider it runs on, as its `SessionStarted` reported it.
     */
    'provider'?: string;
    /**
     * The model it runs on, from its `SessionStarted`; when the start was not seen, the model of its first answer.
     */
    'model'?: string;
    'usage': Usage;
    /**
     * Committed assistant messages.
     */
    'messages': number;
    /**
     * Compactions it completed.
     */
    'compactions': number;
}
