/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Where a session stands, as its events tell it.
 */

export const AgentSessionActivity = {
    IDLE: 'idle',
    RUNNING: 'running',
    WAITING_FOR_STEER: 'waiting_for_steer',
    ENDED: 'ended'
} as const;

export type AgentSessionActivity = typeof AgentSessionActivity[keyof typeof AgentSessionActivity];
