/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentErrorData } from './agent-error-data';
// May contain unused imports in some cases
// @ts-ignore
import type { FailoverStop } from './failover-stop';

/**
 * Why a prompt stayed on its route and ended there although fallback routes were named.
 */
export interface AgentSessionFailoverStop {
    /**
     * The `provider/model` the prompt ended on.
     */
    'route': string;
    /**
     * How many fallback routes the prompt had moved through; `0` on the route it started on.
     */
    'attempt': number;
    'reason': FailoverStop;
    /**
     * The failure that ended the prompt.
     */
    'error': AgentErrorData;
}
