/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompactionReason } from './compaction-reason';
// May contain unused imports in some cases
// @ts-ignore
import type { TokenUsage } from './token-usage';

/**
 * One compaction the root session completed.
 */
export interface AgentSessionCompaction {
    'reason': CompactionReason;
    'original_turn_count': number;
    'preserved_turn_count': number;
    'summary_token_estimate': number;
    'tracked_file_count': number;
    /**
     * The summary call\'s tokens: a breakdown of the session\'s and the prompt\'s usage, which already include them. Zero on compactions recorded before it was kept.
     */
    'usage'?: TokenUsage;
    /**
     * The summary call\'s provider-reported cost, included in the totals the same way.
     */
    'cost_usd_micros'?: number;
}
