/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionCompaction } from './agent-session-compaction';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionDescendantAccount } from './agent-session-descendant-account';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionSubagentCounts } from './agent-session-subagent-counts';
// May contain unused imports in some cases
// @ts-ignore
import type { ContextWindowSnapshot } from './context-window-snapshot';
// May contain unused imports in some cases
// @ts-ignore
import type { Usage } from './usage';

/**
 * What the prompt in progress, or the last one, did: reset when a prompt starts, complete once `completed` is set.
 */
export interface AgentSessionPromptDelta {
    /**
     * Whether the prompt reached its end.
     */
    'completed': boolean;
    /**
     * The root session\'s usage over the prompt.
     */
    'usage': Usage;
    /**
     * Committed assistant messages.
     */
    'messages': number;
    'context_window': ContextWindowSnapshot | null;
    /**
     * Tool calls started, across the tree.
     */
    'tool_calls': number;
    /**
     * Model calls retried after a failed attempt, across the tree.
     */
    'retries'?: number;
    /**
     * Moves the root made to a fallback route during the prompt.
     */
    'failovers'?: number;
    /**
     * What each descendant spent during the prompt, by session id.
     */
    'descendants': { [key: string]: AgentSessionDescendantAccount; };
    /**
     * Child lifecycle events during the prompt.
     */
    'subagents': AgentSessionSubagentCounts;
    /**
     * Compactions the root completed during the prompt.
     */
    'compactions': Array<AgentSessionCompaction>;
    /**
     * Files written or edited during the prompt, across the tree, sorted.
     */
    'files_touched': Array<string>;
    'last_file_touched': string | null;
}
