/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { McpToolSummary } from './mcp-tool-summary';

/**
 * One MCP server the session configured, and whether it has been called. `disconnected` set means the server came up and its connection then closed; otherwise `error` set means it did not start; otherwise it is ready with `tools`.
 */
export interface AgentSessionMcpServer {
    'tools': Array<McpToolSummary>;
    /**
     * Why it did not start, when it did not.
     */
    'error': string | null;
    /**
     * Whether any of its tools has been called.
     */
    'invoked': boolean;
    /**
     * What closed its connection during the session, when it closed.
     */
    'disconnected'?: string;
    /**
     * Milliseconds from launch to its outcome: to its tools being listed, or to the failure. Absent until either has been seen.
     */
    'startup_ms'?: number;
}
