/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionActivatedSkill } from './agent-session-activated-skill';
// May contain unused imports in some cases
// @ts-ignore
import type { SkillSummary } from './skill-summary';

/**
 * The skills the root session found and the ones activated anywhere in the tree.
 */
export interface AgentSessionSkills {
    'available': Array<SkillSummary>;
    'activated': Array<AgentSessionActivatedSkill>;
}
