/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentErrorData } from './agent-error-data';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionSubagentStatusClosed } from './agent-session-subagent-status-closed';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionSubagentStatusCompleted } from './agent-session-subagent-status-completed';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionSubagentStatusFailed } from './agent-session-subagent-status-failed';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionSubagentStatusRunning } from './agent-session-subagent-status-running';

/**
 * @type AgentSessionSubagentStatus
 * Where a child stands.
 */
export type AgentSessionSubagentStatus = { status: 'closed' } & AgentSessionSubagentStatusClosed | { status: 'completed' } & AgentSessionSubagentStatusCompleted | { status: 'failed' } & AgentSessionSubagentStatusFailed | { status: 'running' } & AgentSessionSubagentStatusRunning;
