/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentErrorKind } from './agent-error-kind';
// May contain unused imports in some cases
// @ts-ignore
import type { LlmRetryClassification } from './llm-retry-classification';

/**
 * A failure as the coding agent\'s event stream carries it: category, safe message, retry advice, provider and model context, and the rendered source chain. Never a raw provider response body.
 */
export interface AgentErrorData {
    'kind': AgentErrorKind;
    /**
     * The whole failure rendered for a person, cause included.
     */
    'message': string;
    /**
     * The model-layer category, when a model call failed.
     */
    'llm_kind'?: string;
    /**
     * Whether repeating the same model call is safe, when a model call failed.
     */
    'retry'?: LlmRetryClassification;
    /**
     * The provider that produced the failure, when one was selected.
     */
    'provider'?: string;
    /**
     * The model that produced the failure, when one was selected.
     */
    'model'?: string;
    /**
     * The HTTP status, when the failure came from an HTTP response.
     */
    'status'?: number;
    /**
     * The provider\'s own error code, as reported on the wire.
     */
    'provider_code'?: string;
    /**
     * The provider\'s advised wait in milliseconds.
     */
    'provider_retry_after_millis'?: number;
    /**
     * The text of each cause below `message`, outermost first.
     */
    'source_chain'?: Array<string>;
}
