/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionSubagentStatus } from './agent-session-subagent-status';

/**
 * One child the root spawned. A reused child stays one row; every event after the spawn moves its status.
 */
export interface AgentSessionSubagent {
    'agent_id': string;
    'depth': number;
    'task': string;
    'status': AgentSessionSubagentStatus;
}
