/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionActivity } from './agent-session-activity';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionCompaction } from './agent-session-compaction';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionDescendantAccount } from './agent-session-descendant-account';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionFailoverStop } from './agent-session-failover-stop';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionMcpServer } from './agent-session-mcp-server';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionPromptDelta } from './agent-session-prompt-delta';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionRoute } from './agent-session-route';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionRouteFailover } from './agent-session-route-failover';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionSkills } from './agent-session-skills';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionSubagent } from './agent-session-subagent';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionSubagentCounts } from './agent-session-subagent-counts';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSessionToolActivity } from './agent-session-tool-activity';
// May contain unused imports in some cases
// @ts-ignore
import type { ContextWindowSnapshot } from './context-window-snapshot';
// May contain unused imports in some cases
// @ts-ignore
import type { TodoListProjection } from './todo-list-projection';
// May contain unused imports in some cases
// @ts-ignore
import type { TokenUsage } from './token-usage';

/**
 * The coding agent\'s fold of one stage\'s event stream: token counts and provider-reported cost for the root session and each descendant, the route and where it moved, the context window, tools, MCP servers, skills, todo lists, subagents, compactions, files touched, and the prompt in progress. Counts only; pricing a count from the catalog is fabro\'s, and lives in `StageProjection.usage`.
 */
export interface AgentSessionProjection {
    /**
     * The root session, once an event named it.
     */
    'root_session_id': string | null;
    'route': AgentSessionRoute;
    'activity': AgentSessionActivity;
    /**
     * The root session\'s usage over the stage.
     */
    'usage': TokenUsage;
    /**
     * The root session\'s provider-reported cost, when a provider reported one.
     */
    'cost_usd_micros': number | null;
    /**
     * Committed assistant messages from the root session.
     */
    'messages': number;
    /**
     * Every descendant session\'s account, by session id.
     */
    'descendants': { [key: string]: AgentSessionDescendantAccount; };
    'context_window': ContextWindowSnapshot | null;
    /**
     * Every tool called anywhere in the tree, by the name the model used.
     */
    'tools': { [key: string]: AgentSessionToolActivity; };
    /**
     * Model calls retried after a failed attempt, across the tree.
     */
    'retries'?: number;
    /**
     * Every MCP server the root configured, by name.
     */
    'mcp_servers': { [key: string]: AgentSessionMcpServer; };
    'skills': AgentSessionSkills;
    'subagent_counts': AgentSessionSubagentCounts;
    /**
     * Every todo list in the tree, by list id. The root agent\'s own list is the one whose id ends with `root_session_id`.
     */
    'todos': { [key: string]: TodoListProjection; };
    'subagents': Array<AgentSessionSubagent>;
    /**
     * The root session\'s compactions, in order.
     */
    'compactions': Array<AgentSessionCompaction>;
    /**
     * Every move the root made to a fallback route, in order.
     */
    'failovers'?: Array<AgentSessionRouteFailover>;
    'failover_stopped'?: AgentSessionFailoverStop | null;
    /**
     * Files written or edited across the tree, sorted.
     */
    'files_touched': Array<string>;
    'last_file_touched': string | null;
    /**
     * How many prompts have started.
     */
    'prompts': number;
    'prompt': AgentSessionPromptDelta;
    /**
     * In-flight bookkeeping, not a fact about the session: the paths a write or edit tool call named, by tool call id, between its start and its completion. Present only while such a call is open; a settled projection has no such member.
     */
    'pending_writes'?: { [key: string]: Array<string>; };
}
