/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunTiming } from './run-timing';
// May contain unused imports in some cases
// @ts-ignore
import type { Usage } from './usage';

/**
 * Aggregate usage totals across all runs.
 */
export interface AggregateUsageTotals {
    /**
     * Total number of completed runs.
     */
    'runs': number;
    /**
     * Tokens and cost summed across every completed run.
     */
    'usage': Usage;
    /**
     * Aggregate timing rollup across every completed run. Active timing sums work across stage visits, so `active_time_ms` can exceed `wall_time_ms`.
     */
    'timing': RunTiming;
}
