/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationScheduleTriggerBreaker } from './automation-schedule-trigger-breaker';

/**
 * Cron schedule trigger evaluated in UTC.
 */
export interface AutomationScheduleTrigger {
    'id': string;
    'type': AutomationScheduleTriggerTypeEnum;
    /**
     * When false the schedule never fires. The automation circuit breaker sets this to false when it pauses the trigger; the recorded `breaker` facts distinguish a breaker pause from a manual pause (fabro-3d97).
     */
    'enabled': boolean;
    /**
     * Five-field cron expression evaluated in UTC.
     */
    'expression': string;
    /**
     * Consecutive same-signature parked/failed runs after which the automation circuit breaker pauses this trigger (fabro-3d97). Omitted uses the engine default of 3. Input-only on create and replace; responses echo the configured value.
     */
    'breaker_threshold'?: number;
    'breaker'?: AutomationScheduleTriggerBreaker;
}

export const AutomationScheduleTriggerTypeEnum = {
    SCHEDULE: 'schedule'
} as const;

export type AutomationScheduleTriggerTypeEnum = typeof AutomationScheduleTriggerTypeEnum[keyof typeof AutomationScheduleTriggerTypeEnum];
