/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationProviderWindowState } from './automation-provider-window-state';

/**
 * Cron schedule trigger evaluated in UTC.
 */
export interface AutomationScheduleTrigger {
    'id': string;
    'type': AutomationScheduleTriggerTypeEnum;
    'enabled': boolean;
    /**
     * Five-field cron expression evaluated in UTC.
     */
    'expression': string;
    /**
     * Scheduler-maintained provider window facts (fork, fabro-b869): one fact per provider the provider-window gate last held this trigger\'s fires for. Read-only; input values are stripped.
     */
    'provider_window'?: AutomationProviderWindowState;
}

export const AutomationScheduleTriggerTypeEnum = {
    SCHEDULE: 'schedule'
} as const;

export type AutomationScheduleTriggerTypeEnum = typeof AutomationScheduleTriggerTypeEnum[keyof typeof AutomationScheduleTriggerTypeEnum];
