/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * What a scheduled fire does while a previous run of the same automation is still non-terminal.
 */

export const AutomationOverlapPolicy = {
    SKIP: 'skip',
    FIRE: 'fire'
} as const;

export type AutomationOverlapPolicy = typeof AutomationOverlapPolicy[keyof typeof AutomationOverlapPolicy];
