/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationProviderWindowFact } from './automation-provider-window-fact';

/**
 * The provider-window gate\'s per-trigger read model (fork, fabro-b869): why a schedule is quiet.
 */
export interface AutomationProviderWindowState {
    'providers': Array<AutomationProviderWindowFact>;
}
