/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One provider\'s window as the gate last observed it.
 */
export interface AutomationProviderWindowFact {
    'provider': string;
    'window': AutomationProviderWindowFactWindowEnum;
    'last_probe_at': string;
    'next_probe_at': string;
}

export const AutomationProviderWindowFactWindowEnum = {
    OPEN: 'open',
    CLOSED: 'closed'
} as const;

export type AutomationProviderWindowFactWindowEnum = typeof AutomationProviderWindowFactWindowEnum[keyof typeof AutomationProviderWindowFactWindowEnum];
