/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BillingModelRef } from './billing-model-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { CompletionUsage } from './completion-usage';

/**
 * Usage and cost billed to one model: one response, or one model\'s share of a stage.
 */
export interface BilledModelUsage {
    'model': BillingModelRef;
    'tokens': CompletionUsage;
    /**
     * Cost for `tokens`, when the provider reported one or the catalog could price them. Absent means no cost data, not zero.
     */
    'total_usd_micros'?: number;
}
