/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Specific reason a run is blocked on external intervention, or — for `quota_rate_limit` — waiting on a provider usage window (fabro-e566): a quota-class terminal failure parks the run blocked instead of failed, resumable through the resume route once the window reopens.
 */

export const BlockedReason = {
    HUMAN_INPUT_REQUIRED: 'human_input_required',
    QUOTA_RATE_LIMIT: 'quota_rate_limit'
} as const;

export type BlockedReason = typeof BlockedReason[keyof typeof BlockedReason];
