/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Why a conversation compaction ran.
 */

export const CompactionReason = {
    THRESHOLD: 'threshold',
    MANUAL: 'manual',
    OVERFLOW: 'overflow'
} as const;

export type CompactionReason = typeof CompactionReason[keyof typeof CompactionReason];
