/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GitSourceRunIntent } from './git-source-run-intent';
// May contain unused imports in some cases
// @ts-ignore
import type { RunIntent } from './run-intent';
// May contain unused imports in some cases
// @ts-ignore
import type { RunIntentArgs } from './run-intent-args';
// May contain unused imports in some cases
// @ts-ignore
import type { RunTarget } from './run-target';

/**
 * @type CreateRunRequest
 */
export type CreateRunRequest = GitSourceRunIntent | RunIntent;
