/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Public github.com repository target.
 */
export interface GitRunTarget {
    'kind': GitRunTargetKindEnum;
    /**
     * GitHub repository slug in `owner/name` form.
     */
    'repo': string;
    /**
     * Required branch name, preserved exactly.
     */
    'branch': string;
    /**
     * Optional exact commit. The server lowercase-normalizes its syntax but does not resolve it or prove branch ancestry.
     */
    'sha'?: string;
}

export const GitRunTargetKindEnum = {
    GIT: 'git'
} as const;

export type GitRunTargetKindEnum = typeof GitRunTargetKindEnum[keyof typeof GitRunTargetKindEnum];
