/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunIntentArgs } from './run-intent-args';
// May contain unused imports in some cases
// @ts-ignore
import type { RunTarget } from './run-target';

/**
 * Create a run from a workflow that lives in a git repository: the server checks out the source, registers the immutable workflow versions, and creates the run from the resolved root version — the same resolution automations use. Serves callers whose execution context cannot host the manifest build (e.g. run-tool orchestration from inside a sandbox, fabro-e297).
 */
export interface GitSourceRunIntent {
    /**
     * GitHub repository slug hosting the workflow.
     */
    'repo': string;
    /**
     * Working branch to resolve; branch HEAD is used when `sha` is absent.
     */
    'branch': string;
    /**
     * Optional tag; takes precedence over `branch` when set.
     */
    'tag'?: string | null;
    /**
     * Optional exact commit; when set, `branch` still names the working branch the run reports.
     */
    'sha'?: string | null;
    /**
     * Workflow selector relative to the checkout root (extensionless workflow name or explicit path).
     */
    'workflow': string;
    'target': RunTarget;
    'args': RunIntentArgs;
    /**
     * Server environment catalog ID. Omission selects `default`.
     */
    'environment_id'?: string;
    /**
     * Optional orchestration parent run ID.
     */
    'parent_id'?: string;
    /**
     * Optional explicit run title, normalized by the server.
     */
    'title'?: string;
    /**
     * Optional inline goal override.
     */
    'goal'?: string;
}
