/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaginatedEventList } from './paginated-event-list';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginatedRunStreamList } from './paginated-run-stream-list';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationMeta } from './pagination-meta';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStreamItem } from './run-stream-item';

/**
 * @type ListRunEvents200Response
 */
export type ListRunEvents200Response = PaginatedEventList | PaginatedRunStreamList;
