/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Repeating the call cannot succeed.
 */
export interface LlmRetryClassificationNever {
    'type': LlmRetryClassificationNeverTypeEnum;
}

export const LlmRetryClassificationNeverTypeEnum = {
    NEVER: 'never'
} as const;

export type LlmRetryClassificationNeverTypeEnum = typeof LlmRetryClassificationNeverTypeEnum[keyof typeof LlmRetryClassificationNeverTypeEnum];
