/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Repeating the call is safe after the given delay.
 */
export interface LlmRetryClassificationAfter {
    'type': LlmRetryClassificationAfterTypeEnum;
    /**
     * The delay in milliseconds.
     */
    'after_millis': number;
}

export const LlmRetryClassificationAfterTypeEnum = {
    AFTER: 'after'
} as const;

export type LlmRetryClassificationAfterTypeEnum = typeof LlmRetryClassificationAfterTypeEnum[keyof typeof LlmRetryClassificationAfterTypeEnum];
