/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LlmRetryClassificationAfter } from './llm-retry-classification-after';
// May contain unused imports in some cases
// @ts-ignore
import type { LlmRetryClassificationNever } from './llm-retry-classification-never';
// May contain unused imports in some cases
// @ts-ignore
import type { LlmRetryClassificationSafe } from './llm-retry-classification-safe';

/**
 * @type LlmRetryClassification
 * Whether repeating the same resolved model call is safe.
 */
export type LlmRetryClassification = { type: 'after' } & LlmRetryClassificationAfter | { type: 'never' } & LlmRetryClassificationNever | { type: 'safe' } & LlmRetryClassificationSafe;
