/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Repeating the call is safe on the caller\'s own schedule.
 */
export interface LlmRetryClassificationSafe {
    'type': LlmRetryClassificationSafeTypeEnum;
}

export const LlmRetryClassificationSafeTypeEnum = {
    SAFE: 'safe'
} as const;

export type LlmRetryClassificationSafeTypeEnum = typeof LlmRetryClassificationSafeTypeEnum[keyof typeof LlmRetryClassificationSafeTypeEnum];
