/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Resolved goal kind and content.
 */
export interface ManifestGoal {
    'type': ManifestGoalTypeEnum;
    /**
     * Resolved goal content.
     */
    'text': string;
}

export const ManifestGoalTypeEnum = {
    VALUE: 'value',
    FILE: 'file',
    GRAPH: 'graph'
} as const;

export type ManifestGoalTypeEnum = typeof ManifestGoalTypeEnum[keyof typeof ManifestGoalTypeEnum];
