/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One tool an MCP server advertised, as the coding agent\'s registry named it.
 */
export interface McpToolSummary {
    /**
     * The name the model calls: `mcp__{server}__{tool}`.
     */
    'name': string;
    /**
     * The server\'s own name for the tool.
     */
    'original_name': string;
}
