/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestCreationStatus } from './pull-request-creation-status';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestLink } from './pull-request-link';

/**
 * Durable status for the latest explicit pull request creation requested for a run.
 */
export interface PullRequestCreation {
    /**
     * Stable identifier for one explicit pull request creation request.
     */
    'id': string;
    'status': PullRequestCreationStatus;
    /**
     * Resolved model identifier used to generate the pull request content.
     */
    'model': string;
    /**
     * Whether creation was allowed for a run without a successful conclusion.
     */
    'force': boolean;
    'requested_at': string;
    'updated_at': string;
    'pull_request'?: PullRequestLink | null;
    'error'?: string | null;
}
