/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationTrigger } from './automation-trigger';
// May contain unused imports in some cases
// @ts-ignore
import type { RunTarget } from './run-target';

/**
 * Request body for replacing an automation.
 */
export interface ReplaceAutomationRequest {
    'name': string;
    'description'?: string | null;
    'target': RunTarget;
    /**
     * Workflow slug or path resolved in the selected repository checkout.
     */
    'workflow': string;
    'triggers': Array<AutomationTrigger>;
}
