/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationGitWorkflowSource } from './automation-git-workflow-source';
// May contain unused imports in some cases
// @ts-ignore
import type { AutomationTrigger } from './automation-trigger';
// May contain unused imports in some cases
// @ts-ignore
import type { RunTarget } from './run-target';

/**
 * Request body for replacing an automation.
 */
export interface ReplaceAutomationRequest {
    'name': string;
    'description'?: string | null;
    /**
     * Server-managed Docker or Daytona environment selected when the automation fires.
     */
    'environment_id': string;
    'target': RunTarget;
    /**
     * Workflow slug or path resolved in the run-target checkout when `workflow_source` is omitted, or in the explicit workflow-source checkout when present.
     */
    'workflow': string;
    'workflow_source'?: AutomationGitWorkflowSource;
    /**
     * Overlap policy for scheduled fires (fabro-09ea). `skip` suppresses a scheduled fire while a previous run of this automation is still non-terminal (running, queued, or blocked at a gate that may wait indefinitely); the next tick retries. Omitted or `fire` keeps the default behavior.
     */
    'on_overlap'?: ReplaceAutomationRequestOnOverlapEnum;
    'triggers': Array<AutomationTrigger>;
}

export const ReplaceAutomationRequestOnOverlapEnum = {
    FIRE: 'fire',
    SKIP: 'skip'
} as const;

export type ReplaceAutomationRequestOnOverlapEnum = typeof ReplaceAutomationRequestOnOverlapEnum[keyof typeof ReplaceAutomationRequestOnOverlapEnum];
