/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationGitWorkflowSourceKind } from './automation-git-workflow-source-kind';

/**
 * Workflow source coordinate and exact commit captured when an automation run was created. The requested ref remains available for audit context while `resolved_sha` identifies the immutable source revision that supplied the workflow bytes.
 */
export interface ResolvedAutomationGitWorkflowSource {
    /**
     * GitHub repository slug in `owner/name` form.
     */
    'repo': string;
    'kind': AutomationGitWorkflowSourceKind;
    /**
     * Branch, tag, or commit requested by the automation.
     */
    'ref': string;
    /**
     * Exact lowercase Git commit that supplied the workflow bytes.
     */
    'resolved_sha': string;
}
