/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunGraphEdge } from './run-graph-edge';
// May contain unused imports in some cases
// @ts-ignore
import type { RunGraphNode } from './run-graph-node';

/**
 * The display graph of a run: the admitted workflow\'s name, goal, stages and edges, read off the graph Petri admitted at create time. Lowering artifacts (the goal check, a synthetic fan-in) are left out; the stages are the nodes the workflow declares, imports and `[run.prepare]` steps included.
 */
export interface RunGraph {
    /**
     * The workflow\'s name, the DOT `digraph` name.
     */
    'name': string;
    /**
     * The run\'s goal as the run displays it; empty when the workflow has none.
     */
    'goal'?: string;
    /**
     * The stages by node id.
     */
    'nodes'?: { [key: string]: RunGraphNode; };
    /**
     * The routing edges as written, one per arm.
     */
    'edges'?: Array<RunGraphEdge>;
}
