/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunModelControls } from './run-model-controls';

export interface RunModelSettings {
    'provider': string | null;
    'name': string | null;
    /**
     * Ordered fallback targets keyed by the originally requested model. Each chain is independent; selecting a fallback target does not activate that target model\'s own chain.
     */
    'fallbacks': { [key: string]: Array<string>; };
    'controls'?: RunModelControls;
    /**
     * How long a streaming stage LLM call may wait for its first token before it errors and rides the normal retry/fallback path, in seconds. Null means the engine default (45 s). Applies only to streaming calls; a non-streaming completion has no first-token seam.
     */
    'first_token_timeout_secs': number | null;
}
