/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunTiming } from './run-timing';
// May contain unused imports in some cases
// @ts-ignore
import type { Usage } from './usage';

/**
 * Aggregate usage totals across all stages of a run.
 */
export interface RunUsageTotals {
    /**
     * Run-level timing rollup. `wall_time_ms` is summed across stage visits; active timing sums work across visits.
     */
    'timing': RunTiming;
    /**
     * Tokens and cost summed across every stage visit. The cost is known only when every visit that used tokens was priced.
     */
    'usage': Usage;
}
