/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunUsageStage } from './run-usage-stage';
// May contain unused imports in some cases
// @ts-ignore
import type { RunUsageTotals } from './run-usage-totals';
// May contain unused imports in some cases
// @ts-ignore
import type { UsageByModel } from './usage-by-model';

/**
 * Complete usage breakdown for a single run.
 */
export interface RunUsage {
    /**
     * Per-node usage breakdown. Each row sums usage and runtime across all visits of that node.
     */
    'stages': Array<RunUsageStage>;
    'totals': RunUsageTotals;
    /**
     * Usage grouped by model.
     */
    'by_model': Array<UsageByModel>;
}
