/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Every regular text file under one workspace-relative directory of a run\'s sandbox, keyed by paths relative to the directory\'s parent. Bounded: at most 200 files, 256 KiB per file, 2 MiB total; a violated bound refuses the read instead of truncating it.
 */
export interface RunSandboxFileMap {
    /**
     * The requested workspace-relative directory.
     */
    'directory': string;
    /**
     * File contents keyed by path relative to the directory\'s parent (`<slug>/workflow.toml` for a `.fabro/workflows/<slug>` directory).
     */
    'files': { [key: string]: string; };
}
