/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StageState } from './stage-state';
// May contain unused imports in some cases
// @ts-ignore
import type { StageTiming } from './stage-timing';
// May contain unused imports in some cases
// @ts-ignore
import type { Usage } from './usage';
// May contain unused imports in some cases
// @ts-ignore
import type { UsageModelRef } from './usage-model-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { UsageStageRef } from './usage-stage-ref';

/**
 * Token counts and cost for one workflow node within a run. Rows are grouped by node; usage and timing sum every visit of that node.
 */
export interface RunUsageStage {
    'stage': UsageStageRef;
    'model': UsageModelRef | null;
    'usage': Usage;
    /**
     * Per-node timing summed across every visit. `wall_time_ms` is the sum of visit wall times; the active breakdown sums work timing.
     */
    'timing': StageTiming;
    /**
     * Wall-clock time the latest attempt of this stage started, if known.
     */
    'started_at'?: string | null;
    'state'?: StageState | null;
}
