/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PetriGraphRef } from './petri-graph-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { RunEngineOneOf } from './run-engine-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { RunEngineOneOf1 } from './run-engine-one-of1';

/**
 * @type RunEngine
 * The engine a run was created for. `legacy` is the in-process executor; `petri` names the Petri workflow engine and carries what Petri admitted at create time.
 */
export type RunEngine = RunEngineOneOf | RunEngineOneOf1;
