/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Narrow live sandbox-existence view for run-management callers. Run ids whose sandboxes still exist on this host (stopped counts, removed does not).
 */
export interface RunSandboxAvailability {
    /**
     * Sorted, deduplicated run ids (canonical string form).
     */
    'run_ids': Array<string>;
}
