/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Dependency edge from a dependent seed to its blocker.
 */
export interface SeedGraphEdge {
    /**
     * Id of the seed that is blocked.
     */
    'from': string;
    /**
     * Id of the seed that blocks it.
     */
    'to': string;
}
