/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Tracker seed type (seeds format, sd 0.5.15 compatible).
 */

export const SeedType = {
    TASK: 'task',
    BUG: 'bug',
    FEATURE: 'feature',
    EPIC: 'epic'
} as const;

export type SeedType = typeof SeedType[keyof typeof SeedType];
