/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SeedStatus } from './seed-status';
// May contain unused imports in some cases
// @ts-ignore
import type { SeedType } from './seed-type';

/**
 * One tracker seed as a list-safe summary.
 */
export interface SeedSummary {
    /**
     * Seed identifier (`<project>-<hex4>`).
     */
    'id': string;
    /**
     * Seed title.
     */
    'title': string;
    /**
     * Seed status; null when the record carries none.
     */
    'status'?: SeedStatus;
    /**
     * Seed type; null when the record carries none.
     */
    'type'?: SeedType;
    /**
     * Seed priority band (0 most urgent); null when unset.
     */
    'priority'?: number;
    /**
     * Assignee identifier; null when unassigned.
     */
    'assignee'?: string;
    /**
     * Labels carried by the seed.
     */
    'labels': Array<string>;
    /**
     * Ids of seeds this seed depends on.
     */
    'blockedBy': Array<string>;
    /**
     * Record creation time; null when the record carries none.
     */
    'createdAt'?: string;
    /**
     * Last record update time; null when the record carries none.
     */
    'updatedAt'?: string;
}
