/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SeedStatus } from './seed-status';
// May contain unused imports in some cases
// @ts-ignore
import type { SeedType } from './seed-type';

/**
 * One node of the seed dependency graph.
 */
export interface SeedGraphNode {
    /**
     * Seed identifier.
     */
    'id': string;
    /**
     * Seed title.
     */
    'title': string;
    /**
     * Seed status; null when the record carries none.
     */
    'status'?: SeedStatus;
    /**
     * Seed type; null when the record carries none.
     */
    'type'?: SeedType;
}
