/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SeedGraphEdge } from './seed-graph-edge';
// May contain unused imports in some cases
// @ts-ignore
import type { SeedGraphNode } from './seed-graph-node';

/**
 * Seed dependency graph over the tracker\'s seeds.
 */
export interface SeedGraph {
    'nodes': Array<SeedGraphNode>;
    'edges': Array<SeedGraphEdge>;
}
