/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Reason attached to a successful terminal run status. `publish_blocked` marks a green run whose branch push or pull request failed: the work is done and checkpointed, only the outward delivery is blocked; the run error carries the remediation.
 */

export const SuccessReason = {
    COMPLETED: 'completed',
    PARTIAL_SUCCESS: 'partial_success',
    PUBLISH_BLOCKED: 'publish_blocked'
} as const;

export type SuccessReason = typeof SuccessReason[keyof typeof SuccessReason];
