/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Reason attached to a successful terminal run status. `publish_blocked` marks a green run whose branch push or pull request failed: the work is done and checkpointed, only the outward delivery is blocked; the run error carries the remediation. `boundary` marks a run parked at a declared boundary exit (kind=\"boundary\"): work is preserved, the goal is not terminal, the next run re-enters autonomously; the run error says why it parked.
 */

export const SuccessReason = {
    COMPLETED: 'completed',
    PARTIAL_SUCCESS: 'partial_success',
    PUBLISH_BLOCKED: 'publish_blocked',
    BOUNDARY: 'boundary'
} as const;

export type SuccessReason = typeof SuccessReason[keyof typeof SuccessReason];
