/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Token accounting as the coding agent counts it. The five buckets are disjoint: every token is counted in exactly one, so their plain sum is the total. A bucket that is absent reads as zero.
 */
export interface TokenUsage {
    /**
     * Prompt tokens that were neither read from nor written to a cache.
     */
    'input'?: number;
    /**
     * Completion tokens that are not reasoning tokens.
     */
    'output'?: number;
    /**
     * Completion tokens spent on reasoning, billed at the output rate.
     */
    'reasoning'?: number;
    /**
     * Prompt tokens served from a provider cache.
     */
    'cache_read'?: number;
    /**
     * Prompt tokens written into a provider cache.
     */
    'cache_write'?: number;
}
