/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Usage } from './usage';
// May contain unused imports in some cases
// @ts-ignore
import type { UsageModelRef } from './usage-model-ref';

/**
 * Usage grouped by model.
 */
export interface UsageByModel {
    'model': UsageModelRef;
    /**
     * Number of usage-bearing stage visits that used this model.
     */
    'stages': number;
    'usage': Usage;
}
