/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RelatedWorkflowDiagnostic } from './related-workflow-diagnostic';

/**
 * One diagnostic about a workflow. `rule` is the stable code of the check that raised it: Petri\'s codes (`attractor.*`, `unsupported.*`, `deprecated.*`, `info.*`, `fabro.hooks.*`) for the compile, and `fabro.model.no_ready_provider` for Fabro\'s own provider check.
 */
export interface WorkflowDiagnostic {
    /**
     * The stable code of the check that raised the diagnostic.
     */
    'rule': string;
    'severity': WorkflowDiagnosticSeverityEnum;
    'message': string;
    'node_id'?: string | null;
    'edge'?: Array<string> | null;
    'fix'?: string | null;
    'source_path'?: string | null;
    'line'?: number | null;
    'column'?: number | null;
    'span_start'?: number | null;
    'span_len'?: number | null;
    'related'?: Array<RelatedWorkflowDiagnostic>;
}

export const WorkflowDiagnosticSeverityEnum = {
    ERROR: 'error',
    WARNING: 'warning',
    INFO: 'info'
} as const;

export type WorkflowDiagnosticSeverityEnum = typeof WorkflowDiagnosticSeverityEnum[keyof typeof WorkflowDiagnosticSeverityEnum];
