/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkflowRef {
    'slug': string | null;
    'name': string | null;
    'graph_name': string | null;
    /**
     * Content-derived id of the immutable workflow version this run was created from. Absent for runs created before intent-based runs or without a registered workflow; consumers use it to reject runs whose workflow definition drifted (stale evidence).
     */
    'workflow_version_id'?: string | null;
    /**
     * Number of nodes in the workflow graph.
     */
    'node_count': number;
    /**
     * Number of edges in the workflow graph.
     */
    'edge_count': number;
}
