/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { PaginatedSeedList } from '../models';
// @ts-ignore
import type { SeedDetail } from '../models';
// @ts-ignore
import type { SeedGraph } from '../models';
// @ts-ignore
import type { SeedStatus } from '../models';
// @ts-ignore
import type { SeedType } from '../models';
/**
 * SeedsApi - axios parameter creator
 */
export const SeedsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Read-only seed detail, including the raw record fields for forward compatibility with additive tracker extensions.
         * @summary Get Seed
         * @param {string} id Seed identifier (&#x60;&lt;project&gt;-&lt;hex4&gt;&#x60;).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSeed: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSeed', 'id', id)
            const localVarPath = `/api/v1/seeds/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Read-only dependency graph over the tracker\'s seeds. An edge points from a dependent seed to the seed that blocks it (`blockedBy`). Edges referencing unknown seed ids are dropped; the node set covers every seed in the store.
         * @summary Seed Dependency Graph
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSeedGraph: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/seeds/graph`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Read-only list of tracker seeds served from the configured seeds source (the line repository\'s `.seeds` directory, kept fresh via fetch). Filters compose with AND semantics. The default limit is deliberately generous so tracker-wide views (the seed browser) do not silently hide seeds behind a small page.
         * @summary List Seeds
         * @param {number} [pageLimit] Maximum number of seeds to return per page. Defaults to a generous page so tracker-wide views do not silently hide seeds.
         * @param {number} [pageOffset] Number of items to skip before returning results.
         * @param {SeedStatus} [status] Filter by seed status.
         * @param {SeedType} [type] Filter by seed type.
         * @param {string} [assignee] Exact assignee match; the literal &#x60;none&#x60; matches unassigned seeds.
         * @param {string} [label] Exact label match (a seed must carry the label).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSeeds: async (pageLimit?: number, pageOffset?: number, status?: SeedStatus, type?: SeedType, assignee?: string, label?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/seeds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageLimit !== undefined) {
                localVarQueryParameter['page[limit]'] = pageLimit;
            }

            if (pageOffset !== undefined) {
                localVarQueryParameter['page[offset]'] = pageOffset;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (assignee !== undefined) {
                localVarQueryParameter['assignee'] = assignee;
            }

            if (label !== undefined) {
                localVarQueryParameter['label'] = label;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SeedsApi - functional programming interface
 */
export const SeedsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SeedsApiAxiosParamCreator(configuration)
    return {
        /**
         * Read-only seed detail, including the raw record fields for forward compatibility with additive tracker extensions.
         * @summary Get Seed
         * @param {string} id Seed identifier (&#x60;&lt;project&gt;-&lt;hex4&gt;&#x60;).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSeed(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SeedDetail>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSeed(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SeedsApi.getSeed']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Read-only dependency graph over the tracker\'s seeds. An edge points from a dependent seed to the seed that blocks it (`blockedBy`). Edges referencing unknown seed ids are dropped; the node set covers every seed in the store.
         * @summary Seed Dependency Graph
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSeedGraph(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SeedGraph>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSeedGraph(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SeedsApi.getSeedGraph']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Read-only list of tracker seeds served from the configured seeds source (the line repository\'s `.seeds` directory, kept fresh via fetch). Filters compose with AND semantics. The default limit is deliberately generous so tracker-wide views (the seed browser) do not silently hide seeds behind a small page.
         * @summary List Seeds
         * @param {number} [pageLimit] Maximum number of seeds to return per page. Defaults to a generous page so tracker-wide views do not silently hide seeds.
         * @param {number} [pageOffset] Number of items to skip before returning results.
         * @param {SeedStatus} [status] Filter by seed status.
         * @param {SeedType} [type] Filter by seed type.
         * @param {string} [assignee] Exact assignee match; the literal &#x60;none&#x60; matches unassigned seeds.
         * @param {string} [label] Exact label match (a seed must carry the label).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSeeds(pageLimit?: number, pageOffset?: number, status?: SeedStatus, type?: SeedType, assignee?: string, label?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSeedList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSeeds(pageLimit, pageOffset, status, type, assignee, label, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SeedsApi.listSeeds']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SeedsApi - factory interface
 */
export const SeedsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SeedsApiFp(configuration)
    return {
        /**
         * Read-only seed detail, including the raw record fields for forward compatibility with additive tracker extensions.
         * @summary Get Seed
         * @param {string} id Seed identifier (&#x60;&lt;project&gt;-&lt;hex4&gt;&#x60;).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSeed(id: string, options?: RawAxiosRequestConfig): AxiosPromise<SeedDetail> {
            return localVarFp.getSeed(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Read-only dependency graph over the tracker\'s seeds. An edge points from a dependent seed to the seed that blocks it (`blockedBy`). Edges referencing unknown seed ids are dropped; the node set covers every seed in the store.
         * @summary Seed Dependency Graph
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSeedGraph(options?: RawAxiosRequestConfig): AxiosPromise<SeedGraph> {
            return localVarFp.getSeedGraph(options).then((request) => request(axios, basePath));
        },
        /**
         * Read-only list of tracker seeds served from the configured seeds source (the line repository\'s `.seeds` directory, kept fresh via fetch). Filters compose with AND semantics. The default limit is deliberately generous so tracker-wide views (the seed browser) do not silently hide seeds behind a small page.
         * @summary List Seeds
         * @param {number} [pageLimit] Maximum number of seeds to return per page. Defaults to a generous page so tracker-wide views do not silently hide seeds.
         * @param {number} [pageOffset] Number of items to skip before returning results.
         * @param {SeedStatus} [status] Filter by seed status.
         * @param {SeedType} [type] Filter by seed type.
         * @param {string} [assignee] Exact assignee match; the literal &#x60;none&#x60; matches unassigned seeds.
         * @param {string} [label] Exact label match (a seed must carry the label).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSeeds(pageLimit?: number, pageOffset?: number, status?: SeedStatus, type?: SeedType, assignee?: string, label?: string, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedSeedList> {
            return localVarFp.listSeeds(pageLimit, pageOffset, status, type, assignee, label, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SeedsApi - object-oriented interface
 */
export class SeedsApi extends BaseAPI {
    /**
     * Read-only seed detail, including the raw record fields for forward compatibility with additive tracker extensions.
     * @summary Get Seed
     * @param {string} id Seed identifier (&#x60;&lt;project&gt;-&lt;hex4&gt;&#x60;).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSeed(id: string, options?: RawAxiosRequestConfig) {
        return SeedsApiFp(this.configuration).getSeed(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Read-only dependency graph over the tracker\'s seeds. An edge points from a dependent seed to the seed that blocks it (`blockedBy`). Edges referencing unknown seed ids are dropped; the node set covers every seed in the store.
     * @summary Seed Dependency Graph
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSeedGraph(options?: RawAxiosRequestConfig) {
        return SeedsApiFp(this.configuration).getSeedGraph(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Read-only list of tracker seeds served from the configured seeds source (the line repository\'s `.seeds` directory, kept fresh via fetch). Filters compose with AND semantics. The default limit is deliberately generous so tracker-wide views (the seed browser) do not silently hide seeds behind a small page.
     * @summary List Seeds
     * @param {number} [pageLimit] Maximum number of seeds to return per page. Defaults to a generous page so tracker-wide views do not silently hide seeds.
     * @param {number} [pageOffset] Number of items to skip before returning results.
     * @param {SeedStatus} [status] Filter by seed status.
     * @param {SeedType} [type] Filter by seed type.
     * @param {string} [assignee] Exact assignee match; the literal &#x60;none&#x60; matches unassigned seeds.
     * @param {string} [label] Exact label match (a seed must carry the label).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listSeeds(pageLimit?: number, pageOffset?: number, status?: SeedStatus, type?: SeedType, assignee?: string, label?: string, options?: RawAxiosRequestConfig) {
        return SeedsApiFp(this.configuration).listSeeds(pageLimit, pageOffset, status, type, assignee, label, options).then((request) => request(this.axios, this.basePath));
    }
}
